import { buildPoseidon } from "circomlibjs";

let _poseidon: Awaited<ReturnType<typeof buildPoseidon>> | null = null;
async function poseidon() {
  if (!_poseidon) _poseidon = await buildPoseidon();
  return _poseidon;
}

// Accept bigint directly, decimal strings, or hex strings (with or without 0x)
function toField(val: bigint | string | number): bigint {
  if (typeof val === "bigint") return val;
  if (typeof val === "number") return BigInt(Math.floor(val));
  const s = val.trim();
  if (s.startsWith("0x") || s.startsWith("0X")) return BigInt(s);
  // Pure decimal string?
  if (/^\d+$/.test(s)) return BigInt(s);
  // Otherwise treat as a raw hex string (no 0x prefix)
  return BigInt("0x" + s);
}

export async function poseidonHash(inputs: (bigint | string | number)[]): Promise<bigint> {
  const p = await poseidon();
  const result = p(inputs.map(toField));
  return BigInt(p.F.toString(result));
}

export async function generateMerchantCommitment(
  merchantAddr: string,
  merchantSalt: string,
): Promise<string> {
  // Encode merchant address as a field element (first 31 bytes of UTF-8 hex)
  const addrHex = Buffer.from(merchantAddr).toString("hex").slice(0, 62).padEnd(62, "0");
  const addrBig = BigInt("0x" + addrHex);
  // Salt is already a 64-char hex string
  const saltBig = BigInt("0x" + merchantSalt);
  const commitment = await poseidonHash([addrBig, saltBig]);
  return commitment.toString();
}

export async function generateLeaf(
  subscriberSecret: string,   // 64-char hex (generated by crypto.getRandomValues in browser)
  expiry: number,
  subscriptionId: string,     // e.g. "price-feed-1719999999-abcd"
  merchantCommitment: string, // decimal string returned by generateMerchantCommitment
): Promise<{ leaf: string; leafBuf: Buffer }> {
  // subscriber secret: 64-char hex → BigInt
  const secretBig = BigInt("0x" + subscriberSecret);

  // subscriptionId: arbitrary string → encode as UTF-8, take first 31 bytes → BigInt
  const idHex = Buffer.from(subscriptionId, "utf8").toString("hex").slice(0, 62).padEnd(62, "0");
  const idBig = BigInt("0x" + idHex);

  // merchantCommitment: decimal string from poseidon output
  const commitmentBig = BigInt(merchantCommitment);

  const leaf = await poseidonHash([secretBig, BigInt(expiry), idBig, commitmentBig]);
  const hex = leaf.toString(16).padStart(64, "0");
  return { leaf: leaf.toString(), leafBuf: Buffer.from(hex, "hex") };
}
